name: Testing

on:
  push:
    branches:
      - '**'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          src: "./regional_mom6 ./tests"

  testing:
    needs: formatting
    runs-on: ubuntu-latest
    container: ghcr.io/cosima/regional-test-env:updated
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          auto-activate-base: false
          environment-file: environment-ci.yml
          python-version: ${{ matrix.python-version }}
      - name: Install from source
        run: |
          python -m pip install .
      - name: Install pytest
        run: |
          python -m pip install pytest pytest-cov nbval nbconvert
      - name: Test with pytest
        run: |
          if [[ "${{ matrix.python-version }}" == "3.10" ]]; then
            python -m pytest --cov=regional_mom6 --cov-report=xml tests/
          else
            python -m pytest tests/
          fi
      - name: Test the example notebook
        run: |
          ln -s /data demos/PATH_TO_GLORYS_DATA
          ln -s /data demos/PATH_TO_GEBCO_FILE
          ln -s /build/FRE-NCtools/tools demos/PATH_TO_FRE_TOOLS
          ln -s ../ demos/PATH_TO_REGIONAL_MOM6_CODE
          python -m pytest --nbval --nbval-current-env --cov=regional_mom6 --cov-report=xml demos/reanalysis-forced.ipynb

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: ${{ matrix.python-version == '3.10' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          files: ./coverage.xml
          name: codecov-umbrella

      - name: Evaluate notebooks for documentation
        if: ${{ matrix.python-version == '3.10' }}
        id: evaluate-notebooks
        run: |
          rm -rf demos/mom6_input_directories demos/mom6_run_directories
          python3 -m jupyter nbconvert --to notebook --execute --output-dir=docs/demo_notebooks --ExecutePreprocessor.kernel_name=python3 demos/reanalysis-forced.ipynb

      - uses: actions/upload-artifact@v4
        if: ${{ steps.evaluate-notebooks.conclusion != 'skipped' }}
        with:
          name: notebooks-for-${{ github.sha }}
          path: docs/demo_notebooks
