name: Testing

on:
  push:
    branches:
      - '**'

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          src: "./mom6_regional ./tests"

  testing:
    needs: formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Get date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Conda packages
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ steps.get-date.outputs.today }}-${{ hashFiles('environment-ci.yml') }}
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ steps.get-date.outputs.today }}-${{ hashFiles('pyproject.toml') }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          environment-file: environment-ci.yml
          python-version: ${{ matrix.python-version }}
          use-only-tar-bz2: true
      - name: Install from source
        run: |
          python -m pip install .
      - name: Install pytest
        run: |
          python -m pip install pytest pytest-cov
      - name: Test with pytest
        run: |
          if [[ "${{ matrix.python-version }}" == "3.10" ]]; then
            python -m pytest --cov=mom6_regional --cov-report=xml tests/
          else
            python -m pytest tests/
          fi
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: ${{ matrix.python-version == '3.10' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage/reports/
          env_vars: OS,PYTHON
          files: ./coverage.xml
          name: codecov-umbrella
